// AUTO-GENERATED by `npm run brand` (scripts/generate-brand.ts) — do not edit by hand.
// Inline (not <img>) so "Solutions" and the crossbar dot follow the class-based dark
// theme via currentColor, and so "ADV" / "T" render in the site's Inter webfont.

export function BrandLockup({ className }: { className?: string }) {
  return (
    <svg viewBox="0 -6 977 112" className={className} role="img" aria-label="Advait Solutions" fill="none">
      <g transform="translate(-15.78 3.40) scale(0.92)">
        <path d="M28 105 L60 21 L92 105" fill="none" stroke="#F97316" strokeWidth="13" strokeLinejoin="miter" strokeMiterlimit="2" />
        <circle cx="60" cy="64" r="5" fill="currentColor" />
        <circle cx="60" cy="8" r="6" fill="#F97316" />
      </g>
      <text x="108.8" y="100" fontFamily="Inter, system-ui, sans-serif" fontWeight="800" fontSize="100" letterSpacing="4" fill="#F97316">ADV</text>
      <g transform="translate(340.04 20.0) scale(0.8)" fill="#F97316">
        <path d="M2 100 L30 2 L46 2 L74 100 L50 100 L38 34 L26 100 Z" />
      </g>
      <g transform="translate(407.69 25.0) scale(0.75)" fill="#F97316">
        <rect x="2" y="29" width="22" height="71" rx="1" />
        <rect x="1" y="0" width="24" height="21" rx="4.5" />
      </g>
      <text x="432.4" y="100" fontFamily="Inter, system-ui, sans-serif" fontWeight="800" fontSize="100" letterSpacing="4" fill="#F97316">T</text>
      <text x="522.1" y="100" fontFamily="Inter, system-ui, sans-serif" fontWeight="500" fontSize="100" letterSpacing="0.5" fill="currentColor">Solutions</text>
    </svg>
  );
}

export function BrandLockupStacked({ className }: { className?: string }) {
  return (
    <svg viewBox="0 -11 539 153" className={className} role="img" aria-label="Advait Solutions" fill="none">
      <g transform="translate(-26.38 -10.38) scale(1.4131)">
        <path d="M28 105 L60 21 L92 105" fill="none" stroke="#F97316" strokeWidth="13" strokeLinejoin="miter" strokeMiterlimit="2" />
        <circle cx="60" cy="64" r="5" fill="currentColor" />
        <circle cx="60" cy="8" r="6" fill="#F97316" />
      </g>
      <text x="136.8" y="92" fontFamily="Inter, system-ui, sans-serif" fontWeight="800" fontSize="100" letterSpacing="4" fill="#F97316">ADV</text>
      <g transform="translate(368.01 12.0) scale(0.8)" fill="#F97316">
        <path d="M2 100 L30 2 L46 2 L74 100 L50 100 L38 34 L26 100 Z" />
      </g>
      <g transform="translate(435.66 17.0) scale(0.75)" fill="#F97316">
        <rect x="2" y="29" width="22" height="71" rx="1" />
        <rect x="1" y="0" width="24" height="21" rx="4.5" />
      </g>
      <text x="460.4" y="92" fontFamily="Inter, system-ui, sans-serif" fontWeight="800" fontSize="100" letterSpacing="4" fill="#F97316">T</text>
      <text x="136.8" y="138" fontFamily="Inter, system-ui, sans-serif" fontWeight="500" fontSize="41" letterSpacing="1.6" fill="currentColor">Solutions</text>
    </svg>
  );
}
